apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-nodeport
  labels:
    app: flask-nodeport
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask-nodeport
        octopusexport: OctopusExport
    spec:
      containers:
        - name: hashing
          image: 'jdmedeiros/k8s:hashing'
          ports:
            - containerPort: 5000
              protocol: TCP
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname
