apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-load-balancer
  labels:
    app: flask-load-balancer
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask-load-balancer
        octopusexport: OctopusExport
    spec:
      containers:
        - name: hashing
          image: 'jdmedeiros/k8s:hashing'
          ports:
            - containerPort: 5005
              protocol: TCP
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname
