apiVersion: v1
kind: Service
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: flask-load-balancer
      name: flask-load-balancer
      namespace: default
    spec:
      loadBalancerIP: 3.216.237.112
      ports:
        - port: 5000
          protocol: TCP
          targetPort: 5000
      selector:
        octopusexport: OctopusExport
      type: LoadBalancer
      externalTrafficPolicy: Local
      externalIPs:
        - 3.216.237.112
