apiVersion: v1
kind: Service
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: flask-load-balancer
      name: flask-load-balancer
      namespace: default
    spec:
      loadBalancerIP:
      ports:
        - port: 5002
          protocol: TCP
          targetPort: 5002
      selector:
        octopusexport: OctopusExport
      type: LoadBalancer
      externalIPs:
        - 3.213.153.221
