apiVersion: v1
kind: Service
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: flask-load-balancer
      name: flask-load-balancer
      namespace: default
    spec:
      ports:
        - port: 5000
          protocol: TCP
          targetPort: 5000
      selector:
        octopusexport: OctopusExport
      type: LoadBalancer
      externalIPs: 3.230.45.243