apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-deployment
  labels:
    app: onetimesecret
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: onetimesecret
        octopusexport: OctopusExport
    spec:
      containers:
        - name: onetimesecret
          image: 'dimantl/onetimesecret:latest'
          ports:
            - containerPort: 5050
              protocol: TCP
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname