name: Publish Docker images

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Plik image
      - name: Extract metadata for Plik
        id: meta_plik
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: gonresendes/nginx_proxy
      
      - name: Build and Push Plik Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./nginx_proxy
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta_plik.outputs.tags }}
          labels: ${{ steps.meta_plik.outputs.labels }}

    
     
